################################################################################################
###########################################   LOGIN   ###########################################
################################################################################################

quelp_connect_connectpage:
    path:     /login
    defaults: { _controller: FOSUserBundle:Security:login }


################################################################################################
######################################   HOMEPAGE/REGISTER   ###################################
################################################################################################

quelp_connect_registerpage:
    path:     /
    defaults: { _controller: FOSUserBundle:Registration:register }

################################################################################################
#####################################   MOT DE PASSE OUBLIE   ##################################
################################################################################################

quelp_connect_passwordpage:
    path:     /request
    defaults: { _controller: FOSUserBundle:Resetting:request }

################################################################################################
#####################################   PROFIL   ###############################################
################################################################################################

quelp_connect_profilepage:
    path:     /profile
    defaults: { _controller: FOSUserBundle:Profile:show }

################################################################################################
#####################################   PROFIL   ###############################################
################################################################################################

quelp_connect_editprofile:
    path:     /edit
    defaults: { _controller: FOSUserBundle:Profile:edit }

################################################################################################
#####################################   PROFIL   ###############################################
################################################################################################

quelp_image_murpage:
     path:     /mur
     defaults: { _controller: QuelpImageBundle:Mur:index }