parameters:
#    quelp_connect.example.class: Quelp\ConnectBundle\Example

services:
#    quelp_connect.example:
#        class: %quelp_connect.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
