quelp_image_albumpage:
    path:     /album
    defaults: { _controller: QuelpImageBundle:Album:index }
quelp_image_albumspage:
    path:     /albums
    defaults: { _controller: QuelpImageBundle:Albums:index }